-- Seed data from existing JSON files
-- Run this after schema.sql

-- Products
INSERT INTO products (id, name, slug, size, tagline, description, ingredients, heat, category, image_url, featured) VALUES
(1, 'Spicy Pickles', 'spicy-pickles', '32oz (1QT)', 'The jar that started it all.', 'This is where Big Sexy''s was born. Crisp, crunchy cucumbers hit with a triple threat of serrano, habanero, and fresno peppers — then slow-brined until every single bite snaps with heat and flavor. These aren''t your grandma''s pickles. They''re crunchy, they''re bold, and they don''t apologize. One jar and you''ll understand why people keep coming back.', ARRAY['Cucumber', 'White Vinegar', 'Water', 'Pickling Salt', 'Spicy Peppers (Serrano, Habanero, Fresno)', 'Onion', 'Garlic', 'Dill', 'Seed (Coriander, Celery, Mustard)', 'Calcium Chloride'], 3, 'Signature', '/images/products/spicy-pickles.jpg', true),
(2, 'Semi Sour Pickles', 'semi-sour-pickles', '32oz (1QT)', 'All the crunch. None of the fire.', 'Not everybody wants the heat — and that''s okay. These semi-sours deliver that crisp, tangy, old-school deli crunch you crave. Garlic, dill, and a clean brine let the cucumber do the talking. Stack them on sandwiches, serve them on a snack board, or just eat the whole jar standing in front of the fridge. No judgment here.', ARRAY['Cucumber', 'White Vinegar', 'Water', 'Pickling Salt', 'Onion', 'Garlic', 'Dill', 'Seed (Coriander, Celery, Mustard)', 'Calcium Chloride'], 0, 'Non-Spicy', '/images/products/semi-sour-pickles.jpg', true),
(3, 'Spicy Dilly Beans', 'spicy-dilly-beans', '32oz (1QT)', 'The Bloody Mary''s best friend.', 'The product that got Jesse hooked on brining back in 2008. Whole green beans, brined crispy with garlic, dill, and our signature pepper trio. They snap when you bite them. They burn (just right) going down. Drop one in a Bloody Mary and watch people lose their minds — or just eat them straight from the jar like a savage. Either way, you win.', ARRAY['Green Beans', 'White Vinegar', 'Water', 'Pickling Salt', 'Spicy Peppers (Serrano, Habanero, Fresno)', 'Onion', 'Garlic', 'Dill', 'Calcium Chloride'], 3, 'Signature', '/images/products/spicy-dilly-beans.jpg', true),
(4, 'Pickled Garlic', 'pickled-garlic', '16oz (1/2QT)', 'Pop ''em like candy.', 'Whole peeled cloves, slow-brined with raw honey and our spicy pepper blend until they''re soft, tangy, and absolutely addictive. Pop them straight, smash them into pasta, toss them on pizza, blend them into dressings — these cloves make everything better. If you love garlic, this jar will change your life. Fair warning: one jar is never enough.', ARRAY['Peeled Garlic', 'White Vinegar', 'Water', 'Pickling Salt', 'Spicy Peppers (Serrano, Habanero, Fresno)', 'Raw Honey', 'Seed (Coriander, Celery, Mustard)', 'Calcium Chloride'], 2, 'Garlic', '/images/products/pickled-garlic.jpg', true),
(5, 'Shoyu Garlic', 'shoyu-garlic', '16oz (1/2QT)', 'Umami bomb. Garlic obsession.', 'East meets West in this one. Whole garlic cloves soaked in shoyu soy sauce with a whisper of serrano heat. The result? Deep, savory umami that hits different from anything else in our lineup. Drop them in ramen, toss them into a stir-fry, or just eat them one by one while you cook. Your kitchen is about to smell incredible.', ARRAY['Peeled Garlic', 'Shoyu Soy Sauce', 'White Vinegar', 'Water', 'Pickling Salt', 'Serrano', 'Seed (Celery, Mustard)', 'Calcium Chloride'], 1, 'Garlic', '/images/products/shoyu-garlic.jpg', false),
(8, 'Cowboy Candy', 'cowboy-candy', '16oz (1/2QT)', 'One bite and you''re hooked. Guaranteed.', 'Candied jalapenos glazed with honey, garlic, and a mix of herbs that makes them dangerously addictive. Sweet on the front, heat on the back, and a crunch that doesn''t quit. Pile them on burgers, stir them into cream cheese for the easiest appetizer of your life, or just stand at the counter eating them with a fork. This jar empties fast — you''ve been warned.', ARRAY['Jalapenos', 'White Vinegar', 'Water', 'Pickling Salt', 'Honey', 'Fresno Pepper', 'Onion', 'Garlic', 'Oregano', 'Dill', 'Bay Leaf', 'Calcium Chloride'], 2, 'Sweet Heat', '/images/products/cowboy-candy.jpg', true),
(9, 'Escabeche', 'escabeche', '32oz (1QT)', 'The taqueria essential. Homemade.', 'If you''ve ever been to a real taqueria, you know this one. Carrots and jalapenos brined in a tangy, oregano-seasoned brine — bright, crunchy, and absolutely essential next to anything with a tortilla. Tacos, tortas, burritos, huevos rancheros — escabeche makes them all better. This is the jar that sits on the table and never makes it back to the fridge.', ARRAY['Carrots', 'Jalapenos', 'White Vinegar', 'Water', 'Pickling Salt', 'Onion', 'Garlic', 'Oregano', 'Bay Leaf', 'Calcium Chloride'], 2, 'Traditional', '/images/products/escabeche.jpg', true),
(10, 'Pickled Jalapenos', 'pickled-jalapenos', '16oz (1/2QT)', 'Nachos are calling.', 'Forget those sad, soggy rings from a can. These are crisp, tangy jalapeno slices brined with fresno pepper, garlic, and herbs for a clean, sharp heat that actually tastes like something. Pile them on nachos, layer them on sandwiches, scatter them across pizza — anywhere you want a hit of bright, honest heat. This is what jalapenos are supposed to taste like.', ARRAY['Jalapenos', 'White Vinegar', 'Water', 'Pickling Salt', 'Fresno Pepper', 'Onion', 'Garlic', 'Oregano', 'Dill', 'Bay Leaf', 'Calcium Chloride'], 3, 'Traditional', '/images/products/pickled-jalapenos.jpg', false),
(11, 'Pickled Onions', 'pickled-onions', '16oz (1/2QT)', 'The topping that steals the show.', 'Deep ruby red onions brined in red vinegar with a touch of agave and black peppercorn. They''re tangy, slightly sweet, and impossibly vibrant. Put them on tacos and they''ll outshine the meat. Drop them on a burger and people will ask what your secret is. They make salads look like art. Honestly, these might be the most versatile jar we make.', ARRAY['Red Onion', 'Red Vinegar', 'Water', 'Pickling Salt', 'Agave Nectar', 'Garlic', 'Black Peppercorn', 'Calcium Chloride'], 0, 'Non-Spicy', '/images/products/pickled-onions.jpg', false),
(12, 'Pickled Pineapple', 'pickled-pineapple', '16oz (1/2QT)', 'Tropical heat you didn''t know you needed.', 'Yeah, we pickled pineapple. And it''s incredible. Sweet, tropical chunks hit with serrano, honey, cinnamon, and clove — it''s like a vacation in a jar with a little kick at the end. Game-changer on tacos al pastor, unreal alongside a cheese board, and honestly? It''s dessert and a snack at the same time. This is the jar that makes people say ''wait, WHAT is this?''', ARRAY['Pineapple', 'White Vinegar', 'Water', 'Pickling Salt', 'Serrano', 'Honey', 'Garlic', 'Cinnamon', 'Clove', 'Coriander', 'Calcium Chloride'], 1, 'Sweet Heat', '/images/products/pickled-pineapple.jpg', false),
(13, 'Spicy Pickled Okra', 'spicy-pickled-okra', '32oz (1QT)', 'Southern snap with Big Sexy heat.', 'Whole okra pods, brined crisp with our pepper trio for a Southern-inspired snack that packs serious heat. These snap like a bean, burn like a pepper, and taste like nothing you''ve had before. Perfect in a Bloody Mary, killer on a snack plate, or just eaten one after another while standing at the fridge. The okra haters? They haven''t tried these yet.', ARRAY['Okra', 'White Vinegar', 'Water', 'Pickling Salt', 'Spicy Peppers (Serrano, Habanero, Fresno)', 'Onion', 'Garlic', 'Dill', 'Calcium Chloride'], 3, 'Signature', '/images/products/spicy-pickled-okra.jpg', true),
(14, 'Spicy Pickled Radish', 'spicy-pickled-radish', '16oz (1/2QT)', 'Peppery bite meets pepper heat.', 'Radishes already have a natural kick — so we leaned into it. Pickled in a complex blend of agave, red wine vinegar, and our full pepper trio, these hit you with layers of heat: the radish''s peppery bite first, then the habanero''s slow burn. Crunchy, bright, and relentless. Toss them on tacos, pair with hummus, or brave them solo. Heat seekers, this one''s for you.', ARRAY['Radish', 'White Vinegar', 'Water', 'Pickling Salt', 'Spicy Peppers (Habanero, Serrano, Fresno)', 'Agave Nectar', 'Red Wine Vinegar', 'Black Peppercorn', 'Seed (Coriander, Celery, Mustard, Cumin)', 'Calcium Chloride'], 3, 'Specialty', '/images/products/spicy-pickled-radish.jpg', false),
(15, 'Spicy Pickled Turnip', 'spicy-pickled-turnip', '16oz (1/2QT)', 'The sleeper hit of the lineup.', 'Nobody expects turnips to go this hard. Earthy, crunchy turnip transformed by our fiery pepper trio and a touch of agave sweetness. Inspired by Middle Eastern pickled turnips but with a Big Sexy twist that turns heads at every market. Incredible alongside kebabs, shawarma, falafel — or just on their own as a snack that''ll surprise everyone at the table.', ARRAY['Turnip', 'White Vinegar', 'Water', 'Pickling Salt', 'Spicy Peppers (Habanero, Serrano, Fresno)', 'Agave Nectar', 'Black Peppercorn', 'Seed (Celery, Mustard)', 'Calcium Chloride'], 3, 'Specialty', '/images/products/spicy-pickled-turnip.jpg', false),
(16, 'Spicy Mixed Peppers', 'spicy-mixed-peppers', '16oz (1/2QT)', 'Our hottest jar. You''ve been warned.', 'This is the one. A straight-up medley of serrano, fresno, and habanero peppers brined with garlic, dill, and bay leaf. No filler, no buffer — just pure pepper power. Chop them into salsas, pile them on nachos, blend them into hot sauce, or dare your friends and film the results. Our hottest jar, and the one that heat lovers reach for first.', ARRAY['Spicy Mixed Peppers (Serrano, Fresno, Habanero)', 'White Vinegar', 'Water', 'Pickling Salt', 'Onion', 'Garlic', 'Dill', 'Bay Leaf', 'Calcium Chloride'], 4, 'Spicy', '/images/products/spicy-mixed-peppers.jpg', false),
(19, 'Pickled Okra', 'pickled-okra', '32oz (1QT)', 'Southern charm in every bite.', 'All the snap and crunch of our famous okra, without the heat. These whole okra pods are brined with garlic, dill, and a clean, tangy brine that lets the okra''s natural flavor shine. Perfect for snacking, adding to a relish tray, or anyone who loves okra but wants to skip the spice. Crisp, satisfying, and dangerously easy to eat.', ARRAY['Okra', 'White Vinegar', 'Water', 'Pickling Salt', 'Onion', 'Garlic', 'Dill', 'Calcium Chloride'], 0, 'Non-Spicy', '/images/products/pickled-okra.jpg', false);

-- Reset the product sequence
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));

-- Events
INSERT INTO events (id, name, date, time, location, address, type, description) VALUES
(1, 'Wheat Ridge Farmers Market', '2026-04-05', '9:00 AM - 1:00 PM', 'Wheat Ridge Farmers Market', 'Wheat Ridge, CO', 'market', 'Find us at our home turf farmers market with the full lineup of preserved goods.'),
(2, 'Denver Fest 2026', '2026-06-20', '11:00 AM - 6:00 PM', 'Denver Convention Center', 'Denver, CO', 'festival', 'The biggest food festival in Colorado! Sample our full range and grab exclusive festival jars.'),
(3, 'Arvada Farmers Market', '2026-04-12', '9:00 AM - 1:00 PM', 'Olde Town Arvada', 'Arvada, CO', 'market', 'Catch us in Olde Town Arvada with samples and fresh jars for sale.'),
(4, 'Learn to Preserve Workshop', '2026-05-10', '10:00 AM - 2:00 PM', 'Big Sexy''s Kitchen', 'Wheat Ridge, CO', 'class', 'Hands-on preservation class. Learn the art of brining from Big Sexy himself. $125 per person.'),
(5, 'Golden Farmers Market', '2026-04-19', '8:00 AM - 1:00 PM', 'Golden Farmers Market', 'Golden, CO', 'market', 'Bringing the brine to Golden! Full product lineup plus samples.');

SELECT setval('events_id_seq', (SELECT MAX(id) FROM events));

-- Testimonials
INSERT INTO testimonials (id, quote, author, product) VALUES
(1, 'I''ve tried fancy pickles from all over. Nothing comes close. The crunch is real, the heat sneaks up on you, and the jar was gone in two days.', 'Mike R.', 'Spicy Pickles'),
(2, 'Bought the Cowboy Candy at a market thinking it''d last a week. Mixed it into cream cheese that night and it was gone by Sunday. Already ordered more.', 'Sarah T.', 'Cowboy Candy'),
(3, 'I grabbed the garlic on a whim at a farmers market. Ate half the jar in the parking lot. Now I drive across town to find Jesse and stock up.', 'Carlos M.', 'Pickled Garlic'),
(4, 'You can taste the difference between this and store-bought anything. Jesse puts real love into these jars, and it shows in every bite.', 'Denver Dave', NULL),
(5, 'The Shoyu Garlic is unreal. I put it in ramen, on rice bowls, straight out of the jar — it''s umami in a way I''ve never tasted from a brined product.', 'Kim L.', 'Shoyu Garlic');

SELECT setval('testimonials_id_seq', (SELECT MAX(id) FROM testimonials));

-- Class Info
INSERT INTO class_info (id, title, price, duration, description, what_you_learn, what_you_get, max_students) VALUES
(1, 'Learn to Preserve', 125.00, '4 hours', 'Spend an afternoon with Big Sexy himself and learn how to put up jars like a pro. This isn''t a lecture — you''ll get your hands dirty. We''ll break down the science behind a perfect brine, talk spice blending, and walk through every step from raw produce to sealed jar. You''ll leave with real skills, real jars, and the confidence to start preserving on your own.',
ARRAY['The fundamentals of safe food preservation — no guesswork', 'How to nail your brine ratios every single time', 'Proper sterilization so your jars stay shelf-stable', 'Spice blending and building flavor profiles that pop', 'Hot water bath canning from start to finish', 'Canning basics — from prep to sealed jar', 'Labeling, storage, and how to make your jars last'],
ARRAY['4 hours of real, hands-on instruction — not a demo', 'All materials and ingredients provided (just show up)', '3 jars of your own creations to take home', 'Guidance to creating your very own recipes', 'Education on safe practices for canning vegetables', '10% off your first Big Sexy''s product order'],
12);

-- Create storage bucket for images (run in Supabase dashboard SQL editor)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true);
-- CREATE POLICY "Public read images" ON storage.objects FOR SELECT USING (bucket_id = 'images');
-- CREATE POLICY "Admin upload images" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'images');
-- CREATE POLICY "Admin update images" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'images');
-- CREATE POLICY "Admin delete images" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'images');
